In [23]:
#Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from scipy.stats import skew

pd.set_option('display.max_columns', None)

import copy

In [24]:
#Reading the data files
train = pd.read_csv('Train.csv', index_col='Applicant_ID')

train.head()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
Applicant_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,NaN,NaN,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,NaN,1052.0,8.0000,2.0,NaN,12.0,12.0,4.0,0.0,NaN,NaN,0.392854,2.02,0.711632,0.0,0.0,charge,NaN,1.129518,0.044335,no
Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,14584.29,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,NaN,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,NaN,NaN,0.314281,8.08,0.183584,NaN,0.0,charge,349.805730,1.620483,0.322436,no
Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,192944.0,1079864.0,NaN,NaN,0.0,16576457,22452691.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1597.5,4746.0,3164.0,60.0,15696.0,NaN,14508.0,70.0,0.6666,0.0,NaN,12.0,0.0,6.0,0.0,149.6805,NaN,0.162965,18.18,0.791136,0.0,0.0,charge,NaN,1.513370,0.011640,yes
Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,NaN,771776.0,1186839.0,48187375,136297820.0,0.0,0.0,0.0,1.0,1.0,120.120,8580.00,0.00,85.800,1701.0,4014.0,2676.0,60.0,11679.0,NaN,NaN,522.0,7.8334,1.0,1.0,4.0,8.0,4.0,1.0,NaN,NaN,0.488884,2.02,0.685168,NaN,0.0,charge,89.940100,0.664452,0.082729,no
Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,396391.0,818456.0,511535.0,28141427,15292757.0,0.0,0.0,0.0,3.0,3.0,104.535,8360.19,10326.45,115.335,1551.0,3285.0,2190.0,60.0,19437.0,12958.0,5202.0,272.0,1.0000,0.0,0.0,24.0,2.0,24.0,0.0,150.0135,NaN,0.275000,12.12,0.438168,0.0,0.0,charge,97.887502,1.427891,0.045630,no

In [25]:
train.shape

(56000, 51)

In [26]:
test = pd.read_csv('Test.csv', index_col='Applicant_ID')

test.head()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
Applicant_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,0.0,1649749.0,5446.0,0.0,48187375,114686147.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1086.0,6204.0,2676.0,60.0,14691.0,9794.0,NaN,238.0,1.8334,0.0,NaN,22.0,2.0,14.0,0.0,NaN,NaN,0.825000,1.01,0.800000,NaN,0.0,charge,NaN,0.000000,0.011221
Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,18308285.0,622789.0,1025793.0,1396510.0,34694910,87479487.0,1.0,1.0,1.0,2.0,2.0,142.560,NaN,NaN,570.585,3082.5,10221.0,6814.0,60.0,11955.0,3528.0,NaN,1216.0,19.5000,3.0,NaN,30.0,18.0,14.0,2.0,NaN,18.8415,0.507694,4.04,0.623248,1.0,0.0,lending,NaN,0.504974,0.043525
Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,NaN,0.0,118256.0,NaN,NaN,21973443,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,852.0,4836.0,NaN,NaN,NaN,7.8334,0.0,NaN,2.0,NaN,0.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,charge,NaN,0.000000,NaN
Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,493641.0,1391064.0,1176725.0,1220293.0,16576457,NaN,2.0,2.0,2.0,3.0,3.0,109.005,13050.00,NaN,109.005,1414.5,4197.0,2798.0,60.0,14964.0,NaN,NaN,248.0,9.0000,1.0,1.0,36.0,0.0,26.0,0.0,NaN,NaN,0.916663,2.02,0.464224,NaN,NaN,charge,90.163742,0.788809,0.104029
Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,5752921.0,271133.0,613064.0,4779643.0,48187375,72049802.0,0.0,0.0,0.0,3.0,3.0,139.065,469.29,469.29,15.180,2724.0,9855.0,6570.0,182.0,11679.0,5900.0,NaN,2388.0,16.6666,1.0,0.0,24.0,28.0,20.0,0.0,NaN,NaN,0.234047,23.23,0.726688,0.0,0.0,lending,1303.587148,1.637733,0.163124

In [27]:
#Seperating the Target from the Predictors
y = train[["default_status"]]

y.head(3)

              default_status
Applicant_ID
Apcnt_1000000             no
Apcnt_1000004             no
Apcnt_1000008            yes

In [29]:
train.isna().sum()#Check if missing values exists

form_field1        2529
form_field2        3844
form_field3         355
form_field4         355
form_field5         355
form_field6       13360
form_field7        5163
form_field8       13360
form_field9        8008
form_field10        355
form_field11      31421
form_field12       9895
form_field13       5889
form_field14          0
form_field15      22475
form_field16      13036
form_field17      11151
form_field18      10402
form_field19          4
form_field20        355
form_field21      15854
form_field22      20400
form_field23      28123
form_field24      13297
form_field25       5450
form_field26       7438
form_field27       9299
form_field28        355
form_field29        355
form_field30      25509
form_field31      39408
form_field32       5450
form_field33       1256
form_field34        355
form_field35      23148
form_field36       1995
form_field37       5450
form_field38        355
form_field39       4211
form_field40      43729
form_field41      38229
form_field42       1323
form_field43        568
form_field44       5383
form_field45      31317
form_field46      15904
form_field47          0
form_field48      20889
form_field49        355
form_field50      11056
default_status        0
dtype: int64

In [30]:
#Handling Missing Values
train = train.fillna(-999)
test = test.fillna(-999)

In [31]:
test.isnull().sum()

form_field1     0
form_field2     0
form_field3     0
form_field4     0
form_field5     0
form_field6     0
form_field7     0
form_field8     0
form_field9     0
form_field10    0
form_field11    0
form_field12    0
form_field13    0
form_field14    0
form_field15    0
form_field16    0
form_field17    0
form_field18    0
form_field19    0
form_field20    0
form_field21    0
form_field22    0
form_field23    0
form_field24    0
form_field25    0
form_field26    0
form_field27    0
form_field28    0
form_field29    0
form_field30    0
form_field31    0
form_field32    0
form_field33    0
form_field34    0
form_field35    0
form_field36    0
form_field37    0
form_field38    0
form_field39    0
form_field40    0
form_field41    0
form_field42    0
form_field43    0
form_field44    0
form_field45    0
form_field46    0
form_field47    0
form_field48    0
form_field49    0
form_field50    0
dtype: int64

In [32]:
train.isnull().sum().any()

False

In [33]:
#Join train and test dataset
data = pd.concat([train.drop("default_status", axis=1),test], axis=0)

In [34]:
data.head(3)

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
Applicant_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,-999.00,-999.00,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,-999.0,1052.0,8.0000,2.0,-999.0,12.0,12.0,4.0,0.0,-999.0000,-999.0,0.392854,2.02,0.711632,0.0,0.0,charge,-999.00000,1.129518,0.044335
Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,14584.29,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,-999.0,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,-999.0000,-999.0,0.314281,8.08,0.183584,-999.0,0.0,charge,349.80573,1.620483,0.322436
Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,-999.0,956940.0,-999.0,192944.0,1079864.0,-999.0,-999.0,0.0,16576457,22452691.0,-999.0,-999.0,-999.0,0.0,0.0,-999.000,-999.00,-999.00,-999.000,1597.5,4746.0,3164.0,60.0,15696.0,-999.0,14508.0,70.0,0.6666,0.0,-999.0,12.0,0.0,6.0,0.0,149.6805,-999.0,0.162965,18.18,0.791136,0.0,0.0,charge,-999.00000,1.513370,0.011640

In [35]:
# Creating new features  based on previous observations.
data['Total14&15'] = data['form_field14'] + data['form_field15']
data['Total13&14'] = data['form_field14'] - data['form_field13']
data['Total1&2'] = data['form_field1'] * data['form_field2']
data['Total1%'] = data['form_field14'] / 100
data['Total19&20'] = data['form_field19'] + data['form_field20']
data['Total40&41'] = data['form_field40'] + data['form_field41']
data['Total46&4'] = data['form_field46'] + data['form_field4']

In [36]:
#Handling the Categorical data with LabelEncoder encoding

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
data['form_field47'] = lb.fit_transform(data['form_field47'])

data.head(3)

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,Total14&15,Total13&14,Total1&2,Total1%,Total19&20,Total40&41,Total46&4
Applicant_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,-999.00,-999.00,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,-999.0,1052.0,8.0000,2.0,-999.0,12.0,12.0,4.0,0.0,-999.0000,-999.0,0.392854,2.02,0.711632,0.0,0.0,0,-999.00000,1.129518,0.044335,208556904.0,88499445.0,979.4318,963751.39,6.0,-1998.0000,0.0
Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,14584.29,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,-999.0,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,-999.0000,-999.0,0.314281,8.08,0.183584,-999.0,0.0,0,349.80573,1.620483,0.322436,73311329.0,25999982.0,2329.3440,281414.27,4.0,-1998.0000,0.0
Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,-999.0,956940.0,-999.0,192944.0,1079864.0,-999.0,-999.0,0.0,16576457,22452691.0,-999.0,-999.0,-999.0,0.0,0.0,-999.000,-999.00,-999.00,-999.000,1597.5,4746.0,3164.0,60.0,15696.0,-999.0,14508.0,70.0,0.6666,0.0,-999.0,12.0,0.0,6.0,0.0,149.6805,-999.0,0.162965,18.18,0.791136,0.0,0.0,0,-999.00000,1.513370,0.011640,39029148.0,16576457.0,1763.9622,165764.57,0.0,-849.3195,0.0

In [37]:
#Seperating the Target from the Predictors
#y = train[["default_status"]]

#y.head(3)

In [38]:
y

              default_status
Applicant_ID
Apcnt_1000000             no
Apcnt_1000004             no
Apcnt_1000008            yes
Apcnt_1000012             no
Apcnt_1000016             no
...                      ...
Apcnt_999968              no
Apcnt_999972             yes
Apcnt_999980              no
Apcnt_999988              no
Apcnt_999996              no

[56000 rows x 1 columns]

In [39]:
#Handling the Categorical data with LabelEncoder encoding

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
y = pd.DataFrame(lb.fit_transform(y))

y.head(3)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   0
0  0
1  0
2  1

In [40]:
X = data.iloc[:56000,:]
X_test = data.iloc[-24000:, :]

In [41]:
X.shape, X_test.shape, y.shape

((56000, 57), (24000, 57), (56000, 1))

In [42]:
#Scaling using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X = pd.DataFrame(scaler.fit_transform(X))
X_test = pd.DataFrame(scaler.fit_transform(X_test))

In [43]:
# Normal Train test split
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y[0], test_size=0.3, random_state=42)

In [44]:
#Handling skewed features using log transformation
skew_features = np.abs(data.apply(lambda x: skew(x)).sort_values(ascending=False))
skew_features[:10] # Displaying top ten skewed features

Total1%         105.896380
form_field14    105.896380
Total13&14      105.895083
Total14&15      105.681718
form_field13     50.971965
form_field7      32.941048
form_field48     19.819697
form_field50     17.367354
form_field10     15.432721
form_field11     14.575642
dtype: float64

In [45]:
# Filtering skewed features.
high_skew = skew_features[skew_features > 1]
# Taking indexes of high skew.
skew_index = high_skew.index
#Applying log transformation
for i in skew_index:
    data[i] = np.log1p(data[i])

/usr/local/lib/python3.6/dist-packages/pandas/core/series.py:726: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [46]:
data = data.fillna(-999)

In [49]:
%pip install catboost

Collecting catboost
  Downloading https://files.pythonhosted.org/packages/90/86/c3dcb600b4f9e7584ed90ea9d30a717fb5c0111574675f442c3e7bc19535/catboost-0.24.1-cp36-none-manylinux1_x86_64.whl (66.1MB)
     |████████████████████████████████| 66.1MB 58kB/s
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.18.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Installing collected packages: catboost
Successfully installed catboost-0.24.1

In [50]:
#Importing Other Necessary Libraries
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_val_score

In [51]:
%pip install optuna

Collecting optuna
  Downloading https://files.pythonhosted.org/packages/9f/b1/a5f0574fa0d769bf0a5629722c84bb0af015967191a37401fe8508c5fb6a/optuna-2.1.0.tar.gz (232kB)
     |████████████████████████████████| 235kB 2.8MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cliff
  Downloading https://files.pythonhosted.org/packages/71/06/03b1f92d46546a18eabf33ff7f37ef422c18c93d5a926bf590fee32ebe75/cliff-3.4.0-py3-none-any.whl (76kB)
     |████████████████████████████████| 81kB 3.1MB/s
Collecting colorlog
  Downloading https://files.pythonhosted.org/packages/2a/81/12d77537c82c5d46aa2721dfee25a0e873ef5920ebd0827152f411effb57/colorlog-4.2.1-py2.py3-none-any.whl
Requirement already satisfied: scipy!=1.4.0 in /usr/local/lib/python3.6/dist-packages (from optuna) (1.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from optuna) (1.18.5)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from optuna) (1.3.19)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from optuna) (0.16.0)
Collecting cmaes>=0.6.0
  Downloading https://files.pythonhosted.org/packages/ee/03/5d15a78ca92ac2bf09f466c54c48bb92979dfe19add2dfed415133ba9792/cmaes-0.6.1-py3-none-any.whl
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from optuna) (4.41.1)
Collecting alembic
  Downloading https://files.pythonhosted.org/packages/12/aa/c261dfd7f4ba6ce4701846a2689a46e2a172e012171de4378fc2926e3bf0/alembic-1.4.3-py2.py3-none-any.whl (159kB)
     |████████████████████████████████| 163kB 9.1MB/s
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.6/dist-packages (from optuna) (20.4)
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (2.4.7)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (1.15.0)
Requirement already satisfied: PrettyTable<0.8,>=0.7.2 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (0.7.2)
Collecting pbr!=2.1.0,>=2.0.0
  Downloading https://files.pythonhosted.org/packages/c1/a3/d439f338aa90edd5ad9096cd56564b44882182150e92148eb14ceb7488ba/pbr-5.5.0-py2.py3-none-any.whl (106kB)
     |████████████████████████████████| 112kB 9.0MB/s
Collecting cmd2!=0.8.3,>=0.8.0
  Downloading https://files.pythonhosted.org/packages/c6/94/0f4f16cff4977188d715a95ea3f90f054b7eb73b05afaf51431a3d77b992/cmd2-1.3.11-py3-none-any.whl (133kB)
     |████████████████████████████████| 143kB 8.7MB/s
Requirement already satisfied: PyYAML>=3.12 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna) (3.13)
Collecting stevedore>=2.0.1
  Downloading https://files.pythonhosted.org/packages/b8/a1/004f04ba411a8002b02aadb089fd6868116c12ddc9f6d576175e89d07587/stevedore-3.2.2-py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 2.7MB/s
Collecting Mako
  Downloading https://files.pythonhosted.org/packages/a6/37/0e706200d22172eb8fa17d68a7ae22dec7631a0a92266634fb518a88a5b2/Mako-1.1.3-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 3.1MB/s
Collecting python-editor>=0.3
  Downloading https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from alembic->optuna) (2.8.1)
Collecting colorama>=0.3.7
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting pyperclip>=1.6
  Downloading https://files.pythonhosted.org/packages/f6/5b/55866e1cde0f86f5eec59dab5de8a66628cb0d53da74b8dbc15ad8dabda3/pyperclip-1.8.0.tar.gz
Requirement already satisfied: importlib-metadata>=1.6.0; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (2.0.0)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (0.2.5)
Requirement already satisfied: setuptools>=34.4 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (50.3.0)
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna) (20.2.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.6/dist-packages (from Mako->alembic->optuna) (1.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata>=1.6.0; python_version < "3.8"->cmd2!=0.8.3,>=0.8.0->cliff->optuna) (3.2.0)
Building wheels for collected packages: optuna
  Building wheel for optuna (PEP 517) ... done
  Created wheel for optuna: filename=optuna-2.1.0-cp36-none-any.whl size=321090 sha256=0f98c5d79761ff5286f2ad1215e202ed7976e4f567788c12ef0c75c50f9c3873
  Stored in directory: /root/.cache/pip/wheels/9f/25/24/a165483933b5eefbf4f93c85f3188dc696cbb38620b73ad713
Successfully built optuna
Building wheels for collected packages: pyperclip
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.0-cp36-none-any.whl size=8693 sha256=72f87b14ec7b52ea47cda928e9b6ab2f69501c925409a56680e639c5aa987eeb
  Stored in directory: /root/.cache/pip/wheels/b2/ac/0a/b784f0afe26eaf52e88a7e15c7369090deea0354fa1c6fc689
Successfully built pyperclip
Installing collected packages: pbr, colorama, pyperclip, cmd2, stevedore, cliff, colorlog, cmaes, Mako, python-editor, alembic, optuna
Successfully installed Mako-1.1.3 alembic-1.4.3 cliff-3.4.0 cmaes-0.6.1 cmd2-1.3.11 colorama-0.4.3 colorlog-4.2.1 optuna-2.1.0 pbr-5.5.0 pyperclip-1.8.0 python-editor-1.0.4 stevedore-3.2.2

In [54]:
#Parameter Optimization
import optuna

def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 500,750)
    max_depth = round(trial.suggest_float('max_depth', 1, 32, log=True))
    border_count = trial.suggest_int('border_count', 150, 200)
    subsample= trial.suggest_uniform('subsample', 0.1, 1.0)
    learning_rate = trial.suggest_loguniform('learning_rate', 0.01, 1.0)
    random_strength = trial.suggest_float('random_strength',  0.05,0.1)
    scale_pos_weight = trial.suggest_float('scale_pos_weight', 0.1, 1.0)
    bagging_temperature = trial.suggest_float('bagging_temperature', 0.5,1.0)

    clf = CatBoostClassifier(
        n_estimators=n_estimators, max_depth=max_depth, 
        bagging_temperature=bagging_temperature, scale_pos_weight=scale_pos_weight,
        border_count=border_count, subsample=subsample, learning_rate=learning_rate,
        random_strength=random_strength)
    
    return cross_val_score(
        clf,X,y, n_jobs=-1,scoring='roc_auc',cv=StratifiedKFold(n_splits=3,shuffle=True,random_state=360)).mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

trial = study.best_trial

print('Accuracy: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))
best_cat_params = trial.params

[I 2020-10-03 04:35:55,931] A new study created in memory with name: no-name-bacdb10c-bf76-498d-8d9f-e7c6e7a2244e
[W 2020-10-03 04:35:58,551] Trial 0 failed, because the objective function returned nan.
[I 2020-10-03 04:36:22,964] Trial 1 finished with value: 0.8341981543668565 and parameters: {'n_estimators': 630, 'max_depth': 1.3215952108160223, 'border_count': 186, 'subsample': 0.1507503519458788, 'learning_rate': 0.2536033120747521, 'random_strength': 0.07831614690243224, 'scale_pos_weight': 0.6290813908117887, 'bagging_temperature': 0.5071120167953942}. Best is trial 1 with value: 0.8341981543668565.
[W 2020-10-03 04:36:23,220] Trial 2 failed, because the objective function returned nan.
[I 2020-10-03 04:39:56,955] Trial 3 finished with value: 0.8081704321377795 and parameters: {'n_estimators': 598, 'max_depth': 10.47718767114379, 'border_count': 170, 'subsample': 0.134438773464919, 'learning_rate': 0.3528310456069549, 'random_strength': 0.07131310017341178, 'scale_pos_weight': 0.998057496430522, 'bagging_temperature': 0.7139192811366653}. Best is trial 1 with value: 0.8341981543668565.
[W 2020-10-03 04:39:57,180] Trial 4 failed, because the objective function returned nan.
[I 2020-10-03 04:41:03,160] Trial 5 finished with value: 0.7764674205301226 and parameters: {'n_estimators': 619, 'max_depth': 5.878913566723739, 'border_count': 193, 'subsample': 0.8364739646588533, 'learning_rate': 0.8188328171961162, 'random_strength': 0.06327851364117902, 'scale_pos_weight': 0.9471109379895934, 'bagging_temperature': 0.7258225090977939}. Best is trial 1 with value: 0.8341981543668565.
[I 2020-10-03 04:41:40,106] Trial 6 finished with value: 0.8374661531940388 and parameters: {'n_estimators': 638, 'max_depth': 2.7743338968053988, 'border_count': 170, 'subsample': 0.4463582375271984, 'learning_rate': 0.03154534297117892, 'random_strength': 0.05630343115041279, 'scale_pos_weight': 0.7402613870538367, 'bagging_temperature': 0.6602921069359233}. Best is trial 6 with value: 0.8374661531940388.
[I 2020-10-03 04:42:18,820] Trial 7 finished with value: 0.8351191417685966 and parameters: {'n_estimators': 569, 'max_depth': 3.5555438947331224, 'border_count': 162, 'subsample': 0.7235384897681881, 'learning_rate': 0.01291881617055822, 'random_strength': 0.08854189226084071, 'scale_pos_weight': 0.5823245979428857, 'bagging_temperature': 0.5399380918676346}. Best is trial 6 with value: 0.8374661531940388.
[I 2020-10-03 04:45:01,668] Trial 8 finished with value: 0.7801446440233099 and parameters: {'n_estimators': 680, 'max_depth': 8.77408531507718, 'border_count': 171, 'subsample': 0.8306406795496957, 'learning_rate': 0.9935821721377025, 'random_strength': 0.06475328060139444, 'scale_pos_weight': 0.12995749805285217, 'bagging_temperature': 0.709889345254044}. Best is trial 6 with value: 0.8374661531940388.
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:691: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

[I 2020-10-03 04:50:23,262] Trial 9 finished with value: 0.7969123731744018 and parameters: {'n_estimators': 747, 'max_depth': 10.437962770730145, 'border_count': 190, 'subsample': 0.8812984652246798, 'learning_rate': 0.7640580757184399, 'random_strength': 0.050804469830254204, 'scale_pos_weight': 0.32328886126980566, 'bagging_temperature': 0.7930544975792788}. Best is trial 6 with value: 0.8374661531940388.
[I 2020-10-03 04:50:51,794] Trial 10 finished with value: 0.832646286968937 and parameters: {'n_estimators': 537, 'max_depth': 1.5181928086299805, 'border_count': 196, 'subsample': 0.8963277973620771, 'learning_rate': 0.024166111680371992, 'random_strength': 0.06760595613747801, 'scale_pos_weight': 0.3387842611145346, 'bagging_temperature': 0.9190832930783762}. Best is trial 6 with value: 0.8374661531940388.
[I 2020-10-03 04:53:41,930] Trial 11 finished with value: 0.8396413457668673 and parameters: {'n_estimators': 674, 'max_depth': 8.731460250964751, 'border_count': 189, 'subsample': 0.526309630959231, 'learning_rate': 0.022997523112064894, 'random_strength': 0.05382025161540033, 'scale_pos_weight': 0.9925525028062395, 'bagging_temperature': 0.7476472550026825}. Best is trial 11 with value: 0.8396413457668673.
[W 2020-10-03 04:53:42,154] Trial 12 failed, because the objective function returned nan.
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:691: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

[I 2020-10-03 05:00:16,273] Trial 13 finished with value: 0.8042859857599645 and parameters: {'n_estimators': 653, 'max_depth': 10.839624786312218, 'border_count': 172, 'subsample': 0.10948995061883637, 'learning_rate': 0.528780127532454, 'random_strength': 0.05460682660007702, 'scale_pos_weight': 0.9519008798122506, 'bagging_temperature': 0.9179141157679331}. Best is trial 11 with value: 0.8396413457668673.
[W 2020-10-03 05:00:17,472] Trial 14 failed, because the objective function returned nan.
[W 2020-10-03 05:00:17,698] Trial 15 failed, because the objective function returned nan.
[W 2020-10-03 05:00:17,915] Trial 16 failed, because the objective function returned nan.
[W 2020-10-03 05:00:18,139] Trial 17 failed, because the objective function returned nan.
[W 2020-10-03 05:00:18,376] Trial 18 failed, because the objective function returned nan.
[W 2020-10-03 05:00:18,594] Trial 19 failed, because the objective function returned nan.

Accuracy: 0.8396413457668673
Best hyperparameters: {'n_estimators': 674, 'max_depth': 8.731460250964751, 'border_count': 189, 'subsample': 0.526309630959231, 'learning_rate': 0.022997523112064894, 'random_strength': 0.05382025161540033, 'scale_pos_weight': 0.9925525028062395, 'bagging_temperature': 0.7476472550026825}

In [55]:
best_cat_params["max_depth"] = int(best_cat_params["max_depth"])

In [56]:
# Creating instances for both Kfold and StratifiedKfold
splits = 25

skfold = StratifiedKFold(n_splits=splits , random_state=419, shuffle=True)

In [57]:
#Models used for Voting
cat = CatBoostClassifier(**best_cat_params,random_state=419, verbose=False, thread_count=-1)
rfc = RandomForestClassifier(n_estimators=400, random_state=419, verbose=False, n_jobs=-1)
lgb = LGBMClassifier(n_jobs=-1, n_estimators=400)

In [59]:
from sklearn.metrics import roc_auc_score
def stratified_vote():
    scores, preds = [], []
    i = 1
    for train_split, val_split in skfold.split(X, y):
        x_train, x_test, y_train, y_test = X.iloc[train_split],X.iloc[val_split], y.iloc[train_split],y.iloc[val_split]
        
        vote = VotingClassifier(estimators=[('model1',cat),('model2',rfc),('model3',lgb)], voting='soft')
        vote.fit(x_train, y_train)
        
        #To see how the model performs after splitting
        score = roc_auc_score(y_test,vote.predict_proba(x_test)[:,1])
        pred = vote.predict_proba(X_test)[:,1]
        scores.append(score)
        preds.append(pred)
        print('Roc for {} split: '.format(i), score)
        i += 1
    print('final absolute Roc: ', np.mean(scores))
    final_predictions = np.mean(preds, axis=0)
    return final_predictions

final_predictions = stratified_vote()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 1 split:  0.8331866576935688

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 2 split:  0.8430786353988713

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 3 split:  0.8386514037721522

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 4 split:  0.842353885178858

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 5 split:  0.8487558454556435

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 6 split:  0.8394354713464823

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 7 split:  0.8539369467308587

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 8 split:  0.8425544856861832

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 9 split:  0.8413584321236908

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 10 split:  0.8522501768735656

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 11 split:  0.8431285741830477

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 12 split:  0.8370651870666412

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 13 split:  0.8474663357601964

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 14 split:  0.8353018605948777

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 15 split:  0.8378353632592563

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 16 split:  0.8373603315096855

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 17 split:  0.8392055228634613

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 18 split:  0.8396040755785208

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 19 split:  0.8380680318712912

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 20 split:  0.8448143444507996

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 21 split:  0.8350928897118465

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 22 split:  0.8350110248298342

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 23 split:  0.839660088392529

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 24 split:  0.836641859453078

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Roc for 25 split:  0.8382339159743161
final absolute Roc:  0.8408020538303702

In [60]:
#from google.colab import drive
#drive.mount('/content/drive')

In [62]:
output = pd.read_csv("SampleSubmission.csv")

output.head(3)

    Applicant_ID  default_status
0  Apcnt_1000032               1
1  Apcnt_1000048               1
2  Apcnt_1000052               1

In [63]:
output.default_status = final_predictions

In [64]:
output.to_csv("Submission9.csv", index=False)

In [65]:
output.head()

    Applicant_ID  default_status
0  Apcnt_1000032        0.577519
1  Apcnt_1000048        0.488840
2  Apcnt_1000052        0.407484
3  Apcnt_1000076        0.749297
4  Apcnt_1000080        0.357907